
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chirag Garg
 */
public class AddingBookToIssuedList extends javax.swing.JFrame {

    /**
     * Creates new form AddingBookToIssuedList
     */
    public AddingBookToIssuedList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 204));
        jLabel1.setText("ADDING BOOK TO ISSUED LIST");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 24, 380, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BOOK ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(84, 134, 81, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(84, 92, 76, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(262, 138, 74, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(262, 96, 74, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(123, 216, 63, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(214, 216, 59, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chirag Garg\\Desktop\\New folder\\images (3).jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String bookid=jTextField2.getText();
String userid=jTextField3.getText();
try
{    
Class.forName("java.sql.DriverManager");
Connection con = (Connection)DriverManager.getConnection ("jdbc:mysql://localhost:3306/lms","root","");
Statement stmt1 = (Statement)con.createStatement();
Statement stmt2 = (Statement)con.createStatement();
Statement stmt = (Statement)con.createStatement();
String q1="SELECT * FROM BOOKS WHERE CODE='"+bookid+"';";
ResultSet rs=stmt.executeQuery(q1);
if(rs.next())
{
String q2="select * from teachers where email=\"vanshitayadav@yahoo.com\" UNION "
        + "select * from student where email=\"vanshitayadav@yahoo.com\";";
ResultSet rs2=stmt.executeQuery(q2);
if(rs2.next())
{
String q="INSERT INTO ISSUEDBOOKS VALUES('"+userid+"','"+bookid+"');"; 
stmt.executeUpdate(q); 
JOptionPane.showMessageDialog(this, "BOOK HAS BEEN ADDED TO THE ISSUED LIST");
}
else
    JOptionPane.showMessageDialog(this, "ACCOUNT DOES NOT EXIST");
}
else
    JOptionPane.showMessageDialog(this, "ACCOUNT DOES NOT EXIST");
} 
catch(Exception e)
{ 
    JOptionPane.showMessageDialog (this, e.getMessage()); 
        } 
jTextField2.setText("");
jTextField3.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new ManageLibrary().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingBookToIssuedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingBookToIssuedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingBookToIssuedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingBookToIssuedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingBookToIssuedList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
